package org.ddouglascarr.enums;

public enum IssueStates
{
    ADMISSION,
    DISCUSSION,
    VOTING,
    CANCELED_ISSUE_NOT_ACCEPTED,
    CANCELED_AFTER_REVOCATION_DURING_VERIFICATION,
    CANCELED_NO_INITIATIVE_ADMITTED,
    FINISHED_WITHOUT_WINNER,
    OPEN,
    CLOSED
}
